spring.application.name=eureka
spring.profiles.active=dev

spring.mvc.hiddenmethod.filter.enabled=true

# Database connection settings
# spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.defer-datasource-initialization=true
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/eureka}
spring.datasource.password=${DB_USER:eureka}
spring.datasource.username=${DB_PASSWORD:eureka}
spring.jpa.hibernate.ddl-auto=create-drop

# File upload settings
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=50MB
# Catch the error
server.tomcat.max-swallow-size=-1
server.tomcat.max-part-count=100

#---
spring.config.activate.on-profile=dev

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
spring.thymeleaf.prefix=file:src/main/resources/templates/
spring.web.resources.static-locations=file:src/main/resources/static/
spring.web.resources.cache.period=0
debud=true

spring.devtools.restart.additional-paths=src/main/resources/templates
spring.devtools.restart.exclude=

spring.jpa.properties.hibernate.default-schema=dev

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.transaction=TRACE
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
