spring.application.name=eureka
spring.profiles.active=dev

spring.mvc.hiddenmethod.filter.enabled=true

# Database connection settings
# spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.defer-datasource-initialization=true
spring.datasource.url=${DB_URL}
spring.datasource.password=${DB_USER}
spring.datasource.username=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

#---
spring.config.activate.on-profile=dev

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
spring.thymeleaf.prefix=file:src/main/resources/templates/
spring.web.resources.static-locations=file:src/main/resources/static/
spring.web.resources.cache.period=0
debud=true

spring.devtools.restart.additional-paths=src/main/resources/templates
spring.devtools.restart.exclude=

spring.jpa.properties.hibernate.default-schema=dev

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.transaction=TRACE
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
